### ISSUE TITLE
Can we have file level event ? 

### ISSUE THREAD

**Issue by yujinqiu** [jgvanwyk/SwiftFileSystemEvents#2]
https://github.com/njdehoog/Witness  this repo can get  file level event.

**Comment by jgvanwyk** [comment]
SwiftFileSystemEvents already supports file events. See [`FileSystemEventStream.Flags.fileEvents`](https://swiftpackageindex.com/jgvanwyk/swiftfilesystemevents/master/documentation/swiftfilesystemevents/filesystemeventstream/flags/fileevents)
